config/routes.rb
Rails.application.routes.draw do

  resources :payment_outstandings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'home#index'


  resources :users do
    collection do
      post :search
    end
  end

  resources :customers do
    member do
      get :search_by_mobile
    end
    collection do
      post :search
    end
  end

  resources :complains, except: [:destroy] do
    member do
      get :status_transitions
      post :resend_sms
    end
    collection do
      post :search
    end
  end
end

app/models/complain.rb
class Complain < ApplicationRecord
  MAX_CUSTOMER_TICKETS_PER_DAY = 3

  FIELDS = %i[
    customer_id person_called assigned_to_id subject description priority category
    due_by status_event comment challan_no receiver_name
  ]

  FIELD_OPTIONS = {
      status_event: Constant.TICKET_EVENTS.values,
      priority: Constant.PRIORITY_TYPES.values,
      category: Constant.CATEGORY_TYPES.values,
  }

  belongs_to :customer,                   inverse_of: :complains
  has_many   :complain_status_transitions, inverse_of: :complain
  belongs_to :assigned_to, class_name: "User", foreign_key: :assigned_to_id, optional: true

  belongs_to :created_by, class_name: "User"
  belongs_to :updated_by, class_name: "User"

  validates_presence_of :ticketid, {message: "Ticket Number cannot be blank"}
  validates_presence_of :subject, {message: "Subject cannot be blank"}
  validates_length_of   :subject, maximum: 100, message: "Cannot be more than 100 characters"
  validates_presence_of :description, {message: "Description cannot be blank"}
  validates_presence_of :status, {message: "Status cannot be blank"}
  validates_presence_of :priority , :category


  validate :due_by_is_valid_and_not_in_past, on: :create
  validate :uniqueness_of_challan_no

  def uniqueness_of_challan_no
    return true unless challan_no.present?
    existing = ComplainStatusTransition.find_by challan_no: challan_no
    errors.add(:challan_no, " Is  present, Please Try Diffrent No") if existing.present?
  end

  before_validation { self.ticketid = rand.to_s[2..10] }

  attr_accessor :change_description, :comment, :challan_no, :receiver_name

  scope :active, -> {
    where status: Constant.TICKET_ACTIVE_STATUSES
  }

  scope :resolve, -> {
    where status: Constant.TICKET_STATUSES[:RESOLVED]
  }

  scope :open, -> {
    where status: Constant.TICKET_STATUSES[:OPEN]
  }

  scope :assign, -> {
    where status: Constant.TICKET_STATUSES[:ASSIGNED]
  }
  scope :keep_pending, -> {
    where status: Constant.TICKET_STATUSES[:PENDING]
  }

  scope :close, -> {
    where status: Constant.TICKET_STATUSES[:CLOSED]
  }

  scope :register_today, -> {
    where(created_at: Date.today.all_day)
  }
  scope :in_process, -> {
    where status: Constant.TICKET_STATUSES[:IN_PROCESS]
  }

  scope :overdue, -> {
    where('complains.due_by < ?', Time.zone.now)
  }

  state_machine :status, initial: Constant.TICKET_STATUSES[:OPEN] do

    audit_trail context: [:change_description, :comment, :challan_no, :receiver_name]

    before_transition on: any do |complain, transition|
      case transition.event
      when Constant.TICKET_EVENTS[:ASSIGN]
        complain.change_description = "Ticket Assigned to #{complain.assigned_to.name} by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:REASSIGN]
        complain.change_description = "Ticket Re-assigned to #{complain.assigned_to.name} by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:KEEP_PENDING]
        complain.change_description = "Ticket Kept Pending by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:BACK_TO_IN_PROCESS]
        complain.change_description = "Ticket status changed back to \"In Process\" by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:CANCEL]
        complain.change_description = "Ticket Canceled by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:RESOLVE]
        complain.change_description = "Ticket Resolved by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:REOPEN]
        complain.change_description = "Ticket Re-opened by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:CLOSE]
        complain.change_description = "Ticket Closed by #{complain.updated_by.name}"
      when Constant.TICKET_EVENTS[:EDIT]
        complain.change_description = "Ticket Details Edited by #{complain.updated_by.name}"
      end
    end

    after_transition any => [Constant.TICKET_STATUSES[:IN_PROCESS], Constant.TICKET_STATUSES[:REASSIGNED]] do |complain, transition|
      if [Constant.TICKET_EVENTS[:ASSIGN], Constant.TICKET_EVENTS[:REASSIGN]].include? transition.event
        SendSmsJob.perform_now complain
      end
    end



    before_transition [Constant.TICKET_STATUSES[:ASSIGNED], Constant.TICKET_STATUSES[:REASSIGNED]] => Constant.TICKET_STATUSES[:IN_PROCESS] do |complain, transition|
      complain.assigned_to = User.find(complain.updated_by.id)
    end

    before_transition [Constant.TICKET_STATUSES[:CANCELED], Constant.TICKET_STATUSES[:RESOLVED]] => Constant.TICKET_STATUSES[:REOPENED] do |complain, transition|
      complain.assigned_to = nil
    end

    after_transition any - Constant.TICKET_STATUSES[:RESOLVED] => [Constant.TICKET_STATUSES[:RESOLVED]] do |complain, transition|
      # if complain.subscriber
      #   PreviewSmsTemplate.new(Constant.SMS_TEMPLATES[:complain_RESOLVED], complain.location.sms_templates).perform_for_item_and_send_to_subscriber complain, complain.subscriber
      # end
    end

    event Constant.TICKET_EVENTS[:ASSIGN] do
      transition [Constant.TICKET_STATUSES[:OPEN],
                  Constant.TICKET_STATUSES[:REOPENED]] => Constant.TICKET_STATUSES[:IN_PROCESS]
    end

    event Constant.TICKET_EVENTS[:REASSIGN] do
      transition [Constant.TICKET_STATUSES[:ASSIGNED],
                  Constant.TICKET_STATUSES[:REASSIGNED],
                  Constant.TICKET_STATUSES[:IN_PROCESS],
                  Constant.TICKET_STATUSES[:REJECTED],
                  Constant.TICKET_STATUSES[:PENDING]] => Constant.TICKET_STATUSES[:IN_PROCESS]
    end

    # event Constant.TICKET_EVENTS[:ACCEPT] do
    #   transition [Constant.TICKET_STATUSES[:ASSIGNED],
    #               Constant.TICKET_STATUSES[:REASSIGNED]] => Constant.TICKET_STATUSES[:IN_PROCESS]
    # end

    # event Constant.TICKET_EVENTS[:REJECT] do
    #   transition [Constant.TICKET_STATUSES[:ASSIGNED],
    #               Constant.TICKET_STATUSES[:REASSIGNED]] => Constant.TICKET_STATUSES[:REJECTED]
    # end

    event Constant.TICKET_EVENTS[:KEEP_PENDING] do
      transition [Constant.TICKET_STATUSES[:IN_PROCESS]] => Constant.TICKET_STATUSES[:PENDING]
    end

    event Constant.TICKET_EVENTS[:BACK_TO_IN_PROCESS] do
      transition [Constant.TICKET_STATUSES[:PENDING]] => Constant.TICKET_STATUSES[:IN_PROCESS]
    end
    event Constant.TICKET_EVENTS[:RESOLVE] do
      transition [Constant.TICKET_STATUSES[:PENDING],
                  Constant.TICKET_STATUSES[:ASSIGNED],
                  Constant.TICKET_STATUSES[:IN_PROCESS]] => Constant.TICKET_STATUSES[:RESOLVED]
    end
    event Constant.TICKET_EVENTS[:CANCEL] do
      transition [Constant.TICKET_STATUSES[:OPEN],
                  Constant.TICKET_STATUSES[:REOPENED],
                  Constant.TICKET_STATUSES[:ASSIGNED],
                  Constant.TICKET_STATUSES[:REASSIGNED],
                  Constant.TICKET_STATUSES[:REJECTED],
                  Constant.TICKET_STATUSES[:PENDING],
                  Constant.TICKET_STATUSES[:IN_PROCESS]] => Constant.TICKET_STATUSES[:CANCELED]
    end



    event Constant.TICKET_EVENTS[:REOPEN] do
      transition [Constant.TICKET_STATUSES[:RESOLVED],
                  Constant.TICKET_STATUSES[:CANCELED]] => Constant.TICKET_STATUSES[:REOPENED]
    end

    event Constant.TICKET_EVENTS[:CLOSE] do
      transition [Constant.TICKET_STATUSES[:RESOLVED],
                  Constant.TICKET_STATUSES[:CANCELED]] => Constant.TICKET_STATUSES[:CLOSED]
    end

    event Constant.TICKET_EVENTS[:EDIT] do
      transition all - Constant.TICKET_STATUSES[:CLOSED] => same
    end

    state Constant.TICKET_STATUSES[:ASSIGNED] do
      validates_presence_of :assigned_to, message: "Please select user to assign the ticket to"
    end

    state Constant.TICKET_STATUSES[:REASSIGNED] do
      validates_presence_of :assigned_to, message: "Please select user to reassign the ticket to"
    end
  end

  def due_by_is_valid_and_not_in_past
    if !self.due_by.present?
      errors.add(:due_by, "Please enter the due by date time")
    elsif self.due_by < Time.zone.now
      errors.add(:due_by, "Can't be in the past")
    end
  end

end

app/controllers/complains_controller.rb
class ComplainsController < ApplicationController
  before_action :set_complain, only: [:show, :edit, :update, :status_transitions, :destroy]

  # GET /complains
  # GET /complains.json
  def index
    @datatable = ComplainsDatatable.new view_context
  end

  def search
    render json: ComplainsDatatable.new(view_context)
  end


  # GET /complains/1
  # GET /complains/1.json
  def show
  end

  # GET /complains/new
  def new
    @complain = Complain.new(
        customer_id: params[:customer_id],
        )
    duedate = DateTime.now.end_of_day + 1.day
    @complain.due_by = duedate.strftime('%d-%b-%y %H:%M')
  end

  # GET /complains/1/edit
  def edit
  end

  # POST /complains
  # POST /complains.json
  def create
    @complain = Complain.new(complain_params.merge(
        created_by: current_user,
        ))
    if @complain.save
      flash[:notice] = '@complain is created successfully. '
    else
      flash.now[:alert] = @complain.errors.full_messages.first
    end
  end

  # PATCH/PUT /complains/1
  # PATCH/PUT /complains/1.json
  def update
    respond_to do |format|
      if @complain.update complain_params
        notice = if params[:complain][:status_event] != Constant.TICKET_EVENTS[:EDIT]
                   "Ticket #{@complain.status} successfully."
                 else
                   'Ticket updated successfully.'
                 end
        if @complain.errors.present?
          notice += @complain.errors.full_messages.to_sentence
          format.html { redirect_to @complain, alert: notice }
          format.js { flash.now[:alert] = notice }
          format.json { render json: { message: notice, data: @complain.for_api } }
        else
          format.html { redirect_to @complain, notice: notice }
          format.js { flash.now[:notice] = notice }
          format.json { render json: { message: notice, data: @complain.for_api } }
        end
      else
        alert = @complain.errors.full_messages.first
        format.html { redirect_to @complain, alert: alert }
        format.js { flash.now[:alert] = "Can't update. #{alert}" }
        format.json { render json: { error_message: alert, error_status: :unprocessable_entity }, status: :unprocessable_entity }
      end
    end
  end

  def status_transitions
    render template: 'layouts/audit_trail', locals: { status_transitions: @complain.complain_status_transitions.order("id desc") }, layout: false
  end

  # DELETE /complains/1
  # DELETE /complains/1.json
  def destroy
    @complain.destroy
    respond_to do |format|
      format.html { redirect_to complains_url, notice: 'Complain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complain
      @complain = Complain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complain_params
      params.require(:complain).permit(
          *Complain::FIELDS
      ).merge(
          updated_from_ip: request.remote_ip,
          updated_by: current_user,
          )
    end
end

app/views/complains/_details.html.erb
<div id="complain-details-holder">
  <div class="edit-buttons">
    <%= button_to edit_complain_path(@complain), remote: true,  params: { replace_with: 'details'}, class: 'btn  btn-outline-primary ', "data-disable-with": "<i class='fa fa-spinner fa-spin'></i> Edit", method: :get do %>
      <i class="fas fa-edit" aria-hidden="true"></i> Edit
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Ticket no: &nbsp;</strong>
        <%= @complain.ticketid %>
      </p>

      <p>
        <strong>Customer: &nbsp;</strong>
        <% if  @complain.customer.present? %>
        <%= link_to @complain.customer.name, customer_path(@complain.customer) %>
      <% else %>
        <%= @complain.customer_name %>
      <% end %>
      </p>
      <p>
        <strong>Person Called: &nbsp;</strong>
        <%= @complain.person_called %>
      </p>
      <p>
        <strong>Assigned To: &nbsp;</strong>
        <% if  @complain.assigned_to.present? %>
        <%= link_to @complain.assigned_to.name, user_path(@complain.assigned_to) %>
       <% else %>
        Not Assigned
      <% end %>
      </p>
      <p>
        <strong>Priority: &nbsp;</strong>
        <%= @complain.priority[1..-1].titleize %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Created At: &nbsp;</strong>
        <%= @complain.created_at.to_formatted_s(:short) %>
      </p>
      <p>
        <strong>Due By: &nbsp;</strong>
        <%= @complain.due_by.to_formatted_s(:short) %>
      </p>
      <p>
        <strong>Status: &nbsp;</strong>
        <%= @complain.status.titleize %>
      </p>
      <p>
        <strong>Subject: &nbsp;</strong>
        <%= @complain.subject %>
      </p><p>
      <strong>Description: &nbsp;</strong>
      <%= @complain.description %>
    </p>


    </div>
  </div>

</div>

app/views/complains/_form.html.erb
<div id="complain-details-holder">
  <% if @complain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complain.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @complain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= bootstrap_form_for @complain, layout: :horizontal,  remote: true do |f| %>
    <%= hidden_field_tag :replace_with, params[:replace_with] %>
    <div class="card-body">
      <%= f.select :customer_id, options_from_collection_for_select(Customer.all, :id, :name_and_mobile, f.object.customer_id),  { include_blank: true, label: 'Customer' }, class: "select2", 'data-placeholder': 'Search by Customer Name or Mobile', required: true %>
      <script>
          initializeSelect2();
      </script>
      <%= f.text_field :person_called %>
      <%= f.select :category, Constant.CATEGORY_TYPES.deep_transform_keys{ |key| key.to_s.titleize } %>

      <%= f.select :priority, Constant.PRIORITY_TYPES.deep_transform_keys{ |key| key.to_s.titleize } %>
      <%= f.text_field :due_by, 'data-bootstrap-datepicker': :datetime, icon: 'calendar' %>
      <script>
          initializeDatePicker()
      </script>

      <%= f.text_field :subject %>
      <%= f.text_area :description, rows: "4" %>
    </div>
    <% if @complain.new_record? %>
      <div class="card-footer">
        <button type="submit" class="btn btn-info">Create</button>
        <button type="submit" class="btn btn-default float-right">Cancel</button>
      </div>
    <% else %>
      <div class="offset-sm-4 col-sm-10">
        <button type="submit" class="btn btn-info">Update</button>
        <%= link_to "Cancel", complains_path(@complain, replace_with: params[:replace_with]),  class: "btn btn-danger" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/complains/create.js.erb
<%# TODO: move validation to location_user not to user object %>
<% if @complain.errors.present? %>
  $('#complain-details-holder').replaceWith('<%=j render 'form' %>');
<% else %>
  window.location.assign('<%= complain_path(@complain) %>');
<% end %>

app/views/complains/edit.html.erb
<h1>Editing Complain</h1>

<%= render 'form', complain: @complain %>

<%= link_to 'Show', @complain %> |
<%= link_to 'Back', complains_path %>

app/views/complains/edit.js.erb
<% if params[:replace_with] == "details" %>
$('#complain-details-holder').replaceWith("<%=j render 'form' %>");
<% end %>

app/views/complains/index.html.erb
<%
  page_title "Complains"
  breadcrumb "Dashboard": root_path, "Complains": nil
%>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <%=  link_to new_complain_path, class: "btn  pull-left" do %>
          <i class="fa fa-plus" aria-hidden="true"></i> Add Complain
        <% end %>
        <%= @datatable.render_html search_complains_path(format: :json) %>

      </div>
    </div>
  </div>
</div>

app/views/complains/new.html.erb
<%
  page_title "Complain Create"
  breadcrumb "Dashboard": root_path, "Complains": nil
%>

<div class="row">
  <div class="col-md-8">
    <div class="card card-info">
      <div class="card-header">
        <h3 class="card-title">Create New Complain</h3>
      </div>

      <%= render 'form', complain: @complain %>

    </div>
  </div>
</div>

app/views/complains/show.html.erb
<%
  page_title "Ticket :#{@complain.ticketid}"
  breadcrumb "Dashboard": root_path, "Tickets": complains_path, "Show": nil
%>


<% @complain.status_events.select{ |e| e != Constant.TICKET_EVENTS[:EDIT] && can?(e, @complain) }.each do |event| %>
  <div class="modal fade" tabindex="-1" id="<%= event %>-location-ticket-modal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <%= bootstrap_form_for @complain do |f| %>
          <div class="modal-header">

            <h4 class="modal-title">Change status to: <b><%= event.titleize %></b></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= f.hidden_field :ticketid %>

            <% if Constant.TICKET_EVENTS.values_at(:ASSIGN, :REASSIGN).include? event %>
              <%= f.select :assigned_to_id, options_for_select(User.all.map {|user| [ user.name, user.id ]}), { include_blank: true }, required: true, 'data-select2-initialize': true, 'data-placeholder': 'Select User' %>
              <script>
                  initializeSelect2();
              </script>

            <% end %>

            <%= f.hidden_field :status_event, value: event %>
            <%= f.text_area :comment %>
            <% if Constant.TICKET_EVENTS.values_at(:RESOLVE).include? event %>
              <%= f.text_field :challan_no %>
              <%= f.text_field :receiver_name  %>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
            <%= f.submit Constant.TICKET_EVENT_LABELS[Constant.TICKET_EVENTS.key event], class: 'btn btn-primary pull-right' %>
          </div>
        <% end %>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
<% end %>

<div class="row">
  <div class="col-md-3">

    <!-- Profile Image -->
    <div class="card card-primary card-outline">
      <div class="card-header">
        <h3 class="card-title">Status:  <b><%= @complain.status.titleize %></b></h3>
      </div>
      <div class="card-body box-profile">
        <% @complain.status_events.select{ |e| e != Constant.TICKET_EVENTS[:EDIT] && can?(e, @complain) }.each do |event| %>
          <%= button_tag Constant.TICKET_EVENT_LABELS[Constant.TICKET_EVENTS.key event], class: "btn btn-block btn-primary", "data-toggle": "modal", "data-target": "##{ event }-location-ticket-modal" %>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->


  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        <ul class="nav nav-pills">
          <li class="nav-item"><a class="nav-link active" href="#detail" data-toggle="tab">Details</a></li>
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane active" id="detail">
            <%= render 'details' %>
          </div>
        </div>
        <!-- /.tab-content -->
      </div>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-header p-2">
    <ul class="nav nav-pills">
      <li class="nav-item"><a id="w3s" class="nav-link" href="<%= status_transitions_complain_path @complain %>" data-target="#audit-trail" data-toggle="tabajax">Comments</a></li>
    </ul>
  </div>
  <div class="card-body">
    <div class="tab-content">
      <div class="tab-pane" id="audit-trail">
      </div>
    </div>
    <!-- /.tab-content -->
  </div>
</div>


<script>
    $(document).ready(function() { $('#w3s').trigger('click') });
</script>