config/routes.rb
Rails.application.routes.draw do

  resources :payment_outstandings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'home#index'


  resources :users do
    collection do
      post :search
    end
  end

  resources :customers do
    member do
      get :search_by_mobile
    end
    collection do
      post :search
    end
  end

  resources :complains, except: [:destroy] do
    member do
      get :status_transitions
      post :resend_sms
    end
    collection do
      post :search
    end
  end
end

app/models/payment_outstanding.rb
class PaymentOutstanding < ApplicationRecord
  belongs_to :customer
end

app/controllers/payment_outstandings_controller.rb
class PaymentOutstandingsController < ApplicationController
  before_action :set_payment_outstanding, only: [:show, :edit, :update, :destroy]

  # GET /payment_outstandings
  # GET /payment_outstandings.json
  def index
    @payment_outstandings = PaymentOutstanding.all
  end

  # GET /payment_outstandings/1
  # GET /payment_outstandings/1.json
  def show
  end

  # GET /payment_outstandings/new
  def new
    @payment_outstanding = PaymentOutstanding.new
  end

  # GET /payment_outstandings/1/edit
  def edit
  end

  # POST /payment_outstandings
  # POST /payment_outstandings.json
  def create
    @payment_outstanding = PaymentOutstanding.new(payment_outstanding_params)

    respond_to do |format|
      if @payment_outstanding.save
        format.html { redirect_to @payment_outstanding, notice: 'Payment outstanding was successfully created.' }
        format.json { render :show, status: :created, location: @payment_outstanding }
      else
        format.html { render :new }
        format.json { render json: @payment_outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_outstandings/1
  # PATCH/PUT /payment_outstandings/1.json
  def update
    respond_to do |format|
      if @payment_outstanding.update(payment_outstanding_params)
        format.html { redirect_to @payment_outstanding, notice: 'Payment outstanding was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_outstanding }
      else
        format.html { render :edit }
        format.json { render json: @payment_outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_outstandings/1
  # DELETE /payment_outstandings/1.json
  def destroy
    @payment_outstanding.destroy
    respond_to do |format|
      format.html { redirect_to payment_outstandings_url, notice: 'Payment outstanding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_outstanding
      @payment_outstanding = PaymentOutstanding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_outstanding_params
      params.require(:payment_outstanding).permit(:customer_id, :amount, :due_date, :status)
    end
end

app/helpers/payment_outstandings_helper.rb
module PaymentOutstandingsHelper
end

app/views/payment_outstandings/_form.html.erb
<%= form_with(model: payment_outstanding, local: true) do |form| %>
  <% if payment_outstanding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_outstanding.errors.count, "error") %> prohibited this payment_outstanding from being saved:</h2>

      <ul>
        <% payment_outstanding.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_outstandings/edit.html.erb
<h1>Editing Payment Outstanding</h1>

<%= render 'form', payment_outstanding: @payment_outstanding %>

<%= link_to 'Show', @payment_outstanding %> |
<%= link_to 'Back', payment_outstandings_path %>

app/views/payment_outstandings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Outstandings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Amount</th>
      <th>Due date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_outstandings.each do |payment_outstanding| %>
      <tr>
        <td><%= payment_outstanding.customer_id %></td>
        <td><%= payment_outstanding.amount %></td>
        <td><%= payment_outstanding.due_date %></td>
        <td><%= payment_outstanding.status %></td>
        <td><%= link_to 'Show', payment_outstanding %></td>
        <td><%= link_to 'Edit', edit_payment_outstanding_path(payment_outstanding) %></td>
        <td><%= link_to 'Destroy', payment_outstanding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Outstanding', new_payment_outstanding_path %>

app/views/payment_outstandings/new.html.erb
<h1>New Payment Outstanding</h1>

<%= render 'form', payment_outstanding: @payment_outstanding %>

<%= link_to 'Back', payment_outstandings_path %>

app/views/payment_outstandings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @payment_outstanding.customer_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @payment_outstanding.amount %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @payment_outstanding.due_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment_outstanding.status %>
</p>

<%= link_to 'Edit', edit_payment_outstanding_path(@payment_outstanding) %> |
<%= link_to 'Back', payment_outstandings_path %>