config/routes.rb
Rails.application.routes.draw do

  resources :payment_outstandings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'home#index'


  resources :users do
    collection do
      post :search
    end
  end

  resources :customers do
    member do
      get :search_by_mobile
    end
    collection do
      post :search
    end
  end

  resources :complains, except: [:destroy] do
    member do
      get :status_transitions
      post :resend_sms
    end
    collection do
      post :search
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :complains, foreign_key: "assigned_to_id"
  validates_presence_of      :name
  validates_presence_of     :email, if: :email_required?
  validates_uniqueness_of   :email, allow_blank: true, message: "is already used to register a user", if: :email_changed?
  validates_format_of       :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, allow_blank: true, if: :email_changed?
  validates_presence_of     :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of       :password, within: 8..128, allow_blank: true
  validates :mobile, format: { with: /\A\d{10}\z/, :allow_blank => true, message: "Invalid mobile Number. Please enter 10 digits (for example 9999999999)" }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all
  # end

  def index
    authorize! :index, User
    @datatable = UsersDatatable.new view_context
  end

  def search
    authorize! :index, User
    render json: UsersDatatable.new(view_context)
  end


  # GET /users/1
  # GET /users/1.json
  def show
    authorize! :show, @user
  end

  # GET /users/new
  def new
    authorize! :new, User
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    authorize! :create, User
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User is created successfully. '
    else
      flash.now[:alert] = @user.errors.full_messages.first
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize! :update, @user
    if @user.update(user_params)
      flash.now[:notice] = '@user was successfully updated.'
    else
      flash.now[:alert] = @user.errors.full_messages.first
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize! :destroy, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :mobile, :name, :admin)
    end
end

app/views/users/_change_password.html.erb
<div id='user-details-holder'>
  <%= bootstrap_form_for @user, layout: :horizontal,  remote: true do |f| %>
    <%= hidden_field_tag :replace_with, params[:replace_with] %>
    <div class="card-body">


        <%= f.password_field :password %>
        <%= f.password_field :password_confirmation %>
    </div>

    <div class="offset-sm-4 col-sm-10">
      <button type="submit" class="btn btn-info">Update</button>
      <%= link_to "Cancel", user_path(@user, replace_with: params[:replace_with]),  class: "btn btn-danger" %>
    </div>
   <% end %>

</div>

app/views/users/_details.html.erb
<div id="user-details-holder">

    <div class="edit-buttons">
      <%= button_to edit_user_path(@user), remote: true,  params: { replace_with: 'details'}, class: 'btn  btn-outline-primary ', "data-disable-with": "<i class='fa fa-spinner fa-spin'></i> Edit", method: :get do %>
        <i class="fas fa-edit" aria-hidden="true"></i> Edit
      <% end %>
    </div>
 <div class="row">
   <div class="col-md-6">
     <dl class="dl-horizontal">
       <dt>Name</dt>
       <dd><%= @user.name.titleize %></dd>
       <dt>Mobile</dt>
       <dd><%= @user.mobile %></dd>
       <dt>Email</dt>
       <dd><%= @user.email %></dd>
     </dl>
   </div>
   <div class="col-md-6">
     <dl class="dl-horizontal">
       <dt>Total Assigend Complain</dt>
       <dd><%= 10 %></dd>
       <dt>Total Open Complain</dt>
       <dd><%= 3 %></dd>
       <dt>Total Resolved Complain</dt>
       <dd><%= 7 %></dd>
     </dl>
   </div>
 </div>


</div>

app/views/users/_form.html.erb
<div id='user-details-holder'>
<%= bootstrap_form_for @user, layout: :horizontal,  remote: true do |f| %>
    <%= hidden_field_tag :replace_with, params[:replace_with] %>
  <div class="card-body">
    <%= f.email_field :email %>
    <% if @user.new_record? %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
    <%end %>
    <%= f.text_field :name %>
    <%= f.text_field :mobile %>
    <%= f.check_box :admin %>
  </div>
  <% if @user.new_record? %>
    <div class="card-footer">
      <button type="submit" class="btn btn-info">Create</button>
      <button type="submit" class="btn btn-default float-right">Cancel</button>
    </div>
  <% else %>
    <button type="submit" class="btn btn-info">Update</button>
      <%= link_to "Cancel", user_path(@user, replace_with: params[:replace_with]),  class: "btn" %>
  <% end %>
<% end %>

</div>

<%#= form_with(model: user, local: true) do |form| %>
  <%# if user.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>-->

<!--      <ul>-->
        <%# user.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/users/create.js.erb
<%# TODO: move validation to location_user not to user object %>
<% if @user.errors.present? %>
  $('#user-details-holder').replaceWith('<%=j render 'form' %>');
<% else %>
  window.location.assign('<%= user_path(@user) %>');
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.js.erb
<% if params[:replace_with] == "details" %>
$('#user-details-holder').replaceWith("<%=j render 'form' %>");
<% elsif params[:replace_with] == "change_password" %>
$('#user-details-holder').replaceWith("<%=j render 'change_password' %>");
<% end %>

app/views/users/index.html.erb
<%
  page_title "Users"
  breadcrumb "Dashboard": root_path, "Users": nil
%>




<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <%=  link_to new_user_path, class: "btn  pull-left" do %>
          <i class="fa fa-plus" aria-hidden="true"></i> Add User
        <% end %>
        <%= @datatable.render_html search_users_path(format: :json) %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%
  page_title "User Create"
  breadcrumb "Dashboard": root_path, "Users": nil
%>

<div class="row">
  <div class="col-md-9">
       <div class="card card-info">
         <div class="card-header">
           <h3 class="card-title">Create New User</h3>
         </div>

           <%= render 'form', user: @user %>

       </div>
  </div>
</div>

app/views/users/show.html.erb
<%
  page_title "User #{@user.name}"
  breadcrumb "Dashboard": root_path,  "Users": users_path, "Show": nil
%>

<div class="row">
  <div class="col-md-3">

    <!-- Profile Image -->
    <div class="card card-primary card-outline">
      <div class="card-body box-profile">
        <div class="text-center">
          <img class="profile-user-img img-fluid img-circle" src="<%= asset_path "user.png" %>" alt="User profile picture">
        </div>

        <h3 class="profile-username text-center"><%= @user.name.titleize %></h3>

        <p class="text-muted text-center"><%= enabled_disabled_label @user.admin?, enabled_text: 'Admin', disabled_text: 'Employee' %></p>

        <%= button_to edit_user_path(@user), remote: true, params: { replace_with: 'change_password'},class: 'btn btn-primary btn-block', "data-disable-with": "<i class='fa fa-spinner fa-spin'></i> Edit", method: :get do %>
          <b>Change Password</b>
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->


  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        <ul class="nav nav-pills">
          <li class="nav-item"><a class="nav-link active" href="#detail" data-toggle="tab">Details</a></li>
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane active" id="detail">
            <%= render 'details' %>
          </div>
        </div>
        <!-- /.tab-content -->
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
<% if @user.errors.present? %>
  <% if params[:replace_with] == "details" %>
  $('#user-details-holder').replaceWith("<%=j render 'form' %>");
  <% elsif params[:replace_with] == "change_password" %>
  $('#user-details-holder').replaceWith("<%=j render 'change_password' %>");
  <% end %>
<% else %>
$('#user-details-holder').replaceWith("<%=j render 'details' %>");
<% end %>