config/routes.rb
Rails.application.routes.draw do

  resources :payment_outstandings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'home#index'


  resources :users do
    collection do
      post :search
    end
  end

  resources :customers do
    member do
      get :search_by_mobile
    end
    collection do
      post :search
    end
  end

  resources :complains, except: [:destroy] do
    member do
      get :status_transitions
      post :resend_sms
    end
    collection do
      post :search
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :complains, :inverse_of => :customer

  validates_presence_of      :name, :mobile
  validates :mobile, format: { with: /\A\d{10}\z/, :allow_blank => true, message: "Invalid mobile Number. Please enter 10 digits (for example 9999999999)" }
  validates :alt_mobile, format: { with: /\A\d{10}\z/, :allow_blank => true, message: "Invalid mobile Number. Please enter 10 digits (for example 9999999999)" }
  validates_uniqueness_of   :name, allow_blank: true, message: "is already used to register a customer", if: :name_changed?
  validates_uniqueness_of   :mobile, message: "Mobile already taken. Use diffrent Mobile"

  def name_and_mobile
    "#{name} (#{mobile})"
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @datatable = CustomersDatatable.new view_context
  end


  def search
    render json: CustomersDatatable.new(view_context)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      flash[:notice] = '@customer is created successfully. '
    else
      flash.now[:alert] = @customer.errors.full_messages.first
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    if @customer.update(customer_params)
      flash.now[:notice] = '@customer was successfully updated.'
    else
      flash.now[:alert] = @customer.errors.full_messages.first
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :mobile, :alt_mobile, :due_date, :due_amount, :address)
    end
end

app/views/customers/_details.html.erb
<div id="customer-details-holder">

  <div class="edit-buttons">
    <%= button_to edit_customer_path(@customer), remote: true,  params: { replace_with: 'details'}, class: 'btn  btn-outline-primary ', "data-disable-with": "<i class='fa fa-spinner fa-spin'></i> Edit", method: :get do %>
      <i class="fas fa-edit" aria-hidden="true"></i> Edit
    <% end %>
  </div>
 <div class="row">
   <div class="col-sm-6">
     <p>
       <strong>Company Name:</strong>
       <%= @customer.name %>
     </p>

     <p>
       <strong>Mobile:</strong>
       <%= @customer.mobile %>
     </p>

     <p>
       <strong>Alternet Mobile:</strong>
       <%= @customer.alt_mobile %>
     </p>

     <p>
       <strong>Address:</strong>
       <%= @customer.address %>
     </p>
   </div>
   <div class="col-sm-6">
     <p>
       <strong>Total Comaplain: &nbsp;</strong>
       <%= link_to @customer.complains.count, complains_path(ComplainsDatatable.param_set("customers.name", @customer.name)) %>
     </p>

     <p>
       <strong>Open Complain: &nbsp;</strong>
       <%= link_to @customer.complains.active.count, complains_path(ComplainsDatatable.param_set("customers.name", @customer.name).deep_merge(ComplainsDatatable.param_set("complains.status", "open"))) %>
     </p>

     <p>
       <strong>Resolved Complain: &nbsp;</strong>
       <%= link_to @customer.complains.resolve.count, complains_path(ComplainsDatatable.param_set("customers.name", @customer.name).deep_merge(ComplainsDatatable.param_set("complains.status", "resolved"))) %>
     </p>
     <p>
       <strong>Closed Complain: &nbsp;</strong>
       <%=link_to @customer.complains.close.count, complains_path(ComplainsDatatable.param_set("customers.name", @customer.name).deep_merge(ComplainsDatatable.param_set("complains.status", "closed"))) %>
     </p>
   </div>
 </div>

</div>

app/views/customers/_form.html.erb
<div id='customer-details-holder'>
  <%= bootstrap_form_for @customer,   remote: true do |f| %>
    <%= hidden_field_tag :replace_with, params[:replace_with] %>
    <div class="card-body">
      <%= f.text_field :name, label: "Company name"%>
      <%= f.text_field :mobile %>
      <%= f.text_field :alt_mobile %>
      <%= f.text_field :address %>
    </div>
    <% if @customer.new_record? %>
      <div class="card-footer">
        <button type="submit" class="btn btn-info">Create</button>
        <button type="submit" class="btn btn-default float-right">Cancel</button>
      </div>
    <% else %>
      <div class="offset-sm-4 col-sm-10">
        <button type="submit" class="btn btn-info">Update</button>
        <%= link_to "Cancel", user_path(@customer, replace_with: params[:replace_with]),  class: "btn btn-danger" %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/customers/create.js.erb
<%# TODO: move validation to location_user not to user object %>
<% if @customer.errors.present? %>
  $('#customer-details-holder').replaceWith('<%=j render 'form' %>');
<% else %>
  window.location.assign('<%= customer_path(@customer) %>');
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/edit.js.erb
<% if params[:replace_with] == "details" %>
$('#customer-details-holder').replaceWith("<%=j render 'form' %>");
<% end %>

app/views/customers/index.html.erb
<%
  page_title "Customers"
  breadcrumb "Dashboard": root_path, "Customers": nil
%>


<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <%=  link_to new_customer_path, class: "btn  pull-left" do %>
          <i class="fa fa-plus" aria-hidden="true"></i> Add Customer
        <% end %>
        <%= @datatable.render_html search_customers_path(format: :json) %>

      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<%
  page_title "Customer Create"
  breadcrumb "Dashboard": root_path, "Customers": nil
%>

<div class="row">
  <div class="col-md-7">
    <div class="card card-info">
      <div class="card-header">
        <h3 class="card-title">Create New Customer</h3>
      </div>

      <%= render 'form', customer: @customer %>

    </div>
  </div>
</div>

app/views/customers/show.html.erb
<%
  page_title "Customer :  #{@customer.name}"
  breadcrumb "Dashboard": root_path,  "Customers": customers_path, "Show": nil
%>

<div class="row">
  <div class="col-md-3">

    <!-- Profile Image -->
    <div class="card card-primary card-outline">
      <div class="card-body box-profile">
        <div class="text-center">
          <img class="profile-user-img img-fluid img-circle" src="<%= asset_path "customer.png" %>" alt="User profile picture">
        </div>

        <h3 class="profile-username text-center"><%= @customer.name.titleize %></h3>

        <p class="text-muted text-center"></p>

        <%= link_to new_complain_path(:customer_id => @customer.id),  class: "btn btn-primary btn-block" do %>
          <i class="fa fa-plus" aria-hidden="true"></i>
          Create Complain
        <% end %>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->


  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        <ul class="nav nav-pills">
          <li class="nav-item"><a class="nav-link active" href="#detail" data-toggle="tab">Details</a></li>
        </ul>
      </div>
      <div class="card-body">
        <div class="tab-content">
          <div class="tab-pane active" id="detail">
            <%= render 'details' %>
          </div>
        </div>
        <!-- /.tab-content -->
      </div>
    </div>
  </div>
</div>
<% if @customer.complains.present? %>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <table class='table table-bordered table-striped ' data-datatable='true' >
          <thead>
          <tr>
            <th>Ticket ID</th>
            <th>Person</th>
            <th>Assigned To</th>
            <th>Subject</th>
            <th>Created At</th>
            <th>Status</th>

          </tr>
          </thead>
          <tbody>
          <% @customer.complains.each do |complain| %>
            <tr>
              <td><%= link_to complain.ticketid, complain_path(complain) %></td>
              <td><%= complain.person_called %></td>
              <td><%= complain.assigned_to.name %></td>
              <td><%= complain.subject %></td>
              <td><%= complain.created_at.strftime("%d-%m-%Y %I:%M %p") %></td>
              <td><span class='badge badge-<%= convert_status_to_class(complain.status) %>'><%= complain.status %></span></td>

            </tr>
          <% end %>

          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/update.js.erb
<% if @customer.errors.present? %>
  <% if params[:replace_with] == "details" %>
    $('#customer-details-holder').replaceWith("<%=j render 'form' %>");
  <% end %>
<% else %>
$('#customer-details-holder').replaceWith("<%=j render 'details' %>");
<% end %>